apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/media
  prune: true
  sourceRef:
    kind: GitRepository
    name: mainline
  timeout: 3m0s
  wait: false