apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: 20000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - timeo=600
    - retrans=3
    - rsize=4096
    - wsize=4096
    - noacl
    - nocto
    - noatime
    - nodiratime
  nfs:
    path: /media
    server: netstore.core.sou.oxide.one
