apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  storageClassName: "ceph-nvme"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
status: {}