apiVersion: apps/v1
kind: Deployment
metadata:
  name: searcharr
spec:
  template:
    spec:
      containers:
      - name: searcharr
        image: toddrob/searcharr:latest
        command: 
          - sh 
          - -c 
          - "sleep infinity"
        imagePullPolicy: Always
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/London
        volumeMounts:
        - name: config
          mountPath: /app
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: searcharr-config

# │   searcharr:
#   25   │     container_name: searcharr
#   26   │     image: toddrob/searcharr:latest
#   27   │     volumes:
#   28   │       - /ctr/searcharr/data:/app/data
#   29   │       - /ctr/searcharr/logs:/app/logs
#   30   │       - /ctr/searcharr/settings.py:/app/settings.py
#   31   │ 
#   32   │     environment:
#   33   │       - TZ=Europe/London
#   34   │     restart: unless-stopped