apiVersion: apps/v1
kind: Deployment
metadata:
  name: searcharr
spec:
  template:
    spec:
      containers:
      - name: searcharr
        image: toddrob/searcharr:latest
        imagePullPolicy: Always
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/London
        volumeMounts:
        - name: config
          mountPath: /app
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: searcharr-config