apiVersion: apps/v1
kind: Deployment
metadata:
  name: searcharr
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: searcharr
        image: toddrob/searcharr:latest
        imagePullPolicy: Always
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/London
        volumeMounts:
        - name: config
          mountPath: /app/data
          subPath: data
        - name: config
          mountPath: /app/logs
          subPath: logs
        - name: config
          mountPath: /app/settings.py
          subPath: settings.py
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: searcharr-config