apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault.oxide.one"
      path: "gecko-secrets"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "24a097ea-cea7-b163-5fdc-117c2dd365e3"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "vault-approle"
            key: "secret_id"
            namespace: "external-secrets"
