apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault.oxide.one"
      path: "gecko-secrets"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "gecko"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          #serviceAccountRef:
          #  name: "vault-auth"
          #  namespace: "external-secrets"
          secretRef:
            name: "vault-auth"
            key: "token"
            namespace: "external-secrets"
