apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-webhook
  namespace: monitoring
  labels:
    alertmanager: main
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'discord'
  receivers:
  - name: 'discord'
    discordConfigs:
    - apiURL:
        key: url
        name: discord-webhook
      sendResolved: true