apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-webhook
  namespace: monitoring
  labels:
    alertmanager: main
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'discord'
  receivers:
  - name: 'discord'
    discordConfigs:
    - apiURL:
        key: url
        name: discord-webhook
      sendResolved: true
      title: 'DevOops! {{ .GroupLabels.SortedPairs.Values | join " " }}'
      message: |
        {{ range .Alerts.Firing }}
          Alert: **{{ printf "%.150s" .Annotations.summary }}** ({{ .Labels.severity }})
          Description: {{ printf "%.150s" .Annotations.description }}
          Alertname: {{ .Labels.alertname }}
          Namespace: {{ .Labels.namespace }}
          Service: {{ .Labels.service }}
        {{ end }}

        {{ if gt (len .Alerts.Resolved) 0 }}
            Also {{ .Alerts.Resolved | len }} resolved alerts.
        {{ end }}