apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-webhook-alertmanager
  namespace: monitoring
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: discord-webhook
    creationPolicy: 'Owner'
  data:
  - secretKey: url
    remoteRef:
      key: discord-webhook
      property: url
