

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: cloudflare
  name: monitoring
  namespace: monitoring
spec:
  rules:
  - host: grafana.oxide.one
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: grafana
            port:
              number: 3000
  - host: alertmanager.oxide.one
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: prometheus-k8s
            port:
              number: 9090
  - host: prometheus.oxide.one
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
            service:
              name: alertmanager-main
              port:
                number: 8080
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - prometheus.oxide.one
    - alertmanager.oxide.one
    - prometheus.oxide.one
    secretName: monitoring-ingress