resources:
- https://github.com/prometheus-operator/kube-prometheus
- ingress.yaml
- networkpolicy.yaml
- mikrotik
#namespace: monitoring
  # - target:
  #     version: v1
  #     kind: Secret
  #     name: grafana-config
  #   path: grafana-config.yaml
patches:
- patch: |-
    apiVersion: monitoring.coreos.com/v1
    kind: Alertmanager
    metadata:
      name: main
    spec:
      externalUrl: https://monitoring.oxide.one/alertmanager/
      routePrefix: /alertmanager
  target:
    kind: Alertmanager
    name: main
- patch: |-
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    metadata:
      name: k8s
    spec:
      externalUrl: https://monitoring.oxide.one/prometheus
      routePrefix: /prometheus
  target:
    kind: Prometheus
    name: k8s
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: grafana-config
      namespace: monitoring
    $patch: delete
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: grafana-datasources
      namespace: monitoring
    $patch: delete
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: grafana-dashboards
      namespace: monitoring
    $patch: delete
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: grafana
      namespace: monitoring
    $patch: delete
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: grafana
      namespace: monitoring
    $patch: delete
- patch: |-
    apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: grafana-rules
      namespace: monitoring
    $patch: delete
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: grafana
      namespace: monitoring
    $patch: delete
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: grafana
      namespace: monitoring
    $patch: delete
- patch: |-
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: grafana
      namespace: monitoring
    $patch: delete
# Remove Grafana resources from remote
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
