resources:
- https://github.com/prometheus-operator/kube-prometheus
- ingress.yaml
- networkpolicy.yaml
#namespace: monitoring
patches:
  - target:
      version: v1
      kind: Secret
      name: grafana-config
    path: grafana-config.yaml
  - target: 
      kind: Alertmanager
      name: main
    patch: |-
      apiVersion: monitoring.coreos.com/v1
      kind: Alertmanager
      metadata:
        name: main
      spec:
        externalUrl: https://monitoring.oxide.one/alertmanager/
  - target: 
      kind: Prometheus
      name: k8s
    patch: |-
      apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      metadata:
        name: k8s
      spec:
        externalUrl: https://monitoring.oxide.one/prometheus/