apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  deployment:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: grafana
  config:
    date_formats:
      default_timezone: Europe/London
    server:
      domain: monitoring.oxide.one
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: "true"
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: admin
      admin_password: admin