apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  storageClassName: "ceph-nvme"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
status: {}