---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ceph-cluster
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./infrastructure/ceph-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: mainline
  targetNamespace: rook-ceph
  timeout: 3m0s
  wait: true