---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ceph-cluster
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/ceph-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: mainline
  targetNamespace: rook-ceph
  timeout: 10m
  validation: server
  #wait: true
  healthChecks:
      - apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: cephblockpools.ceph.rook.io