apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  targetNamespace: ingress
  install:
    createNamespace: true  
  interval: 5m
  chart:
    spec:
      chart: haproxy-ingress
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: flux-system
      interval: 1m
  values:
    controller:
      ingressClassResource:
        enabled: true
        default: true
        controllerClass: "haproxy-ingress"
        parameters: {}
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 100m
          memory: 64Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 11
        targetCPUUtilizationPercentage: 50
        targetMemoryUtilizationPercentage: 50
      publishService:
        enabled: true
      service:
        externalIPs: 
          - 145.40.188.100
        type: ClusterIP
      stats:
        enabled: true
      metrics:
        enabled: true
      serviceMonitor:
        enabled: true
      logs:
        enabled: true