apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvdp
  namespace: flux-system
spec:
  targetNamespace: nvdp
  install:
    createNamespace: true  
  interval: 5m
  chart:
    spec:
    # 
      chart: nvidia-device-plugin
      #version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
      interval: 1m
  values:
    runtimeClassName: nvidia
    nodeSelector:
      gpu: nvidia