apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nvidia-runtimeclass
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/nvidia
  prune: true
  sourceRef:
    kind: GitRepository
    name: mainline
  targetNamespace: kube-system
  timeout: 3m0s
  wait: true