apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  install:
    createNamespace: true  
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      #version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 1m
  # values:
  #   replicaCount: 2
