apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  acme:
    email: okami@doubledash.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: cloudflare-accountkey
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-token
            key: token