apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mktxp-config
    creationPolicy: 'Owner'
  data:
  - secretKey: mktxp.conf
    remoteRef:
      key: mktxp
      property: mktxp.conf
  - secretKey: _mktxp.conf
    remoteRef:
      key: mktxp
      property: _mktxp.conf