apiVersion: apps/v1
kind: Deployment
metadata:
  name: mktxp
  labels:
    app.kubernetes.io/component: mktxp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: mktxp
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mktxp
    spec:
      volumes:
      - name: mktxp
        secret:
          secretName: mktxp
      containers:
      - name: mktxp
        image: ghcr.io/akpw/mktxp:latest
        ports:
        - containerPort: 49090
          name: prometheus
        volumeMounts:
        - name: mktxp
          readOnly: true
          mountPath: "/root/mktxp/"
