apiVersion: v1
kind: Service
metadata:
  name: mktxp
  labels:
    app.kubernetes.io/component: mktxp
spec:
  selector:
    app.kubernetes.io/component: mktxp
  ports:
  - port: 49090
    targetPort: 49090
    name: prometheus
