apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels: 
    app.kubernetes.io/component: mktxp
  name: mktxp
spec:
  endpoints:
  - port: prometheus    
  selector:
    matchLabels:
      app.kubernetes.io/component: mktxp