resources:
- https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/generic-kuberouter-all-features.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: kube-router-cfg
  behavior: merge
  namespace: kube-system
  files:
    - kubeconfig

patches:
  - target: 
      kind: DaemonSet
      name: kube-router
    patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: kube-router
      spec:
        template:
          spec:
            volumes:
            - hostPath:
                path: /opt/cni/bin
                type: ""
              name: cni-plugin
            initContainers:
              - command:
                - /install-cni.sh
                image: ghcr.io/siderolabs/install-cni:v1.5.0
                imagePullPolicy: IfNotPresent
                name: install-cni-sidero
                resources: {}
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
                volumeMounts:
                - mountPath: /host/opt/cni/bin/
                  name: cni-plugin

  # containers:
  #   - name: kube-router
  #     args:
  #     - "--run-router=true"
  #     - "--run-firewall=true"
  #     - "--run-service-proxy=true"
  #     - "--bgp-graceful-restart=true"
  #     - "--kubeconfig=/var/lib/kube-router/kubeconfig"
  #     - "--peer-router-asns=65010"
  #     - "--peer-router-ips=10.0.5.1"
  #     - "--router-id=65015"